### ISSUE TITLE
Configuring the Application Insights TelemetryClient to enrich Request logging

### ISSUE THREAD

**Issue by zippy1981** [serilog/serilog-settings-configuration#107]
Using the [Application insight Sink](https://github.com/serilog/serilog-sinks-applicationinsights) configured via appsettings.json I'd like to do the following:

1. Set User.Id
1. Send full request and response to Application Insights request table in the custom dimensions fields
1. Send everything that gets sent to CustomDimensions on the `trace`, `exceptions` and `customEvents` tables to the request table

For option 1 and 2 there might be a way to do that via a callback hook. OTOH, if there was some static property somewhere that exposed the Sinks Telemetry client too.

Option 3 feels like it could be a configuration flag in [public static LoggerConfiguration ApplicationInsights( . . .)](https://github.com/serilog/serilog-sinks-applicationinsights/blob/master/src/Serilog.Sinks.ApplicationInsights/LoggerConfigurationApplicationInsightsExtensions.cs#L48). I could make the same argument about option 2, but then maybe we need a configuration PODO with several things we could want.

**Comment by MV10** [comment]
In terms of setting User.Id, that's more of an ASP.NET pipeline issue than a config issue. I'm guessing you're talking about something similar to this:

```csharp
telemetry.Context.User.Id = (string)HttpContext.Current.Session["UserId"];
```

Awhile back I asked a question that seems simlar about logging IP addresses and Nick suggested [this](https://github.com/serilog/serilog-aspnetcore/issues/38#issuecomment-370669529), which eventually turned into the following (this was ASP.NET Core 2.0, I'm not sure whether anything changes in 2.1, this project was abandoned so I haven't tried this exact code recently):

```csharp
public static IApplicationBuilder UseSerilogIPLogging(this IApplicationBuilder app)
{
    return
        app.Use(async (ctx, next) => {
            string ip = ctx.Request.Headers["CF_CONNECTING_IP"]; // cloudflare passthrough
            if(string.IsNullOrEmpty(ip)) ip = ctx.Connection.RemoteIpAddress.ToString();
            using(LogContext.PushProperty("IPAddress", ip))
            {
                await next();
            }
    });
```

The other two sound like things that must be handled internally by the sink. All the Serilog configuration packages do is match up `WriteTo` entries with the sink's `LoggerConfiguration` extension method whose argument list most closely matches the arguments in configuration. So if you need a new way to configure the sink, that's a request for the sink's repo.

That being said, if the new configuration requirements are complex, it may be easiest to add a single config argument that accepts an `IConfigurationSection` object (from the _Microsoft.Extensions.Configuration_ packages) then parses that bit of configuration within the sink, rather than adding tons of new individual arguments. You can see an example of this [here](https://github.com/serilog/serilog-sinks-mssqlserver/blob/cca2fc0ed053b92bc7acd80e404f1a83ea37fd2e/src/Serilog.Sinks.MSSqlServer/Configuration/Microsoft.Extensions.Configuration/LoggerConfigurationMSSqlServerExtensions.cs#L64), which is an optional `IConfigurationSection` argument in the SQL sink. The SQL `ColumnOptions` object is pretty complex, and you can see from the couple hundred lines of code [here](https://github.com/serilog/serilog-sinks-mssqlserver/blob/cca2fc0ed053b92bc7acd80e404f1a83ea37fd2e/src/Serilog.Sinks.MSSqlServer/Configuration/Microsoft.Extensions.Configuration/LoggerConfigurationMSSqlServerExtensions.cs#L167) that the processing is also complex -- more than could be reasonably achieved through automated method-signature resolution.

That does tie the sink more tightly to _Microsoft.Extensions.Configuration_ (at least, for the `LoggerConfiguration` override that can handle a config section), but in the case of App Insights that shouldn't be much of a concern.
