### ISSUE TITLE
Documenting examples better?

### ISSUE THREAD

**Issue by zippy1981** [serilog/serilog-settings-configuration#108]
After struggling and pestering you guys for a few days, I'd like to contribute to better examples for this. I'm not sure where. A few ideas:

* I can add more to the Readme file. But we need a little more than that.
* Do you intentionally not create wiki pages?
* Is there another place to create documentation?

I made my own [example app](github.com/justaprogrammer/serilog-aspnetcore-appsettings-sample) that makes creative user of `appsettings.Development.json` to hide secrets (Application Insights Key). Of course then I added the `appsettings.Development.json` to .gitignore to hide the sauce.

I'm going to keep that example for myself, but I could add that sort of stuff to your sample app. I could also store Environment variables in the launch config.

Just looking for thoughts on where you think docs should go.

**Comment by MV10** [comment]
I think it's probably the "moving target" problem.

A few days ago I noticed there is some sort of Serilog documentation repo out there from two years ago... and it's empty.  😁

**Comment by tsimbalar** [comment]
There is an issue tracking that effort, here : serilog/serilog#1053 , but it is quite hard to track the progress of all the possible sinks and configurations ...

**Comment by merbla** [comment]
@zippy1981 you raise a valid point.  

The history of Serilog is that some time ago, sinks and the core library lived together in one repository.  Driven by that setup the [wiki](https://github.com/serilog/serilog/wiki) became the de facto location for information.   Once the sinks were split into separate repositories (now 60+) and the further fragmentation due to .Net Core we now find ourselves with a wide spread of information covering many uses cases.

Also the differing release cadence of sinks, releases of .Net Core and ASP.Net makes it troublesome not only to consolidate documentation but to document a set version of frameworks and technologies.  A good example of this is the churn between [Serilog.Extensions.Logging](https://github.com/serilog/serilog-extensions-logging), [Microsoft.Extensions.Logging](https://github.com/aspnet/Logging) and [Serilog.AspNetCore](https://github.com/serilog/serilog-aspnetcore).

Take the following example:

* A .Net Core app (e.g. the [Serilog](https://github.com/serilog/serilog) repo)
* Using ASP.Net Core (e.g. the [Serilog.AspNetCore](https://github.com/serilog/serilog-aspnetcore) repo)
* Using `appsettings.json` (e.g. the [Serilog.Settings.Configuration](https://github.com/serilog/serilog-settings-configuration) repo)

What is a good home for this sort of information and documentation? Which version of .Net Core is being used? Which version of ASP.Net is being used? 

All these factors make it hard to consolidate the information and more importantly keep it relevant.

Personally, in the early days I used [Nick's blog](https://nblumhardt.com/
) as the goto place for some of my niche use cases.  Recently I have extended to the [Docker repository](https://github.com/serilog/serilog-docker) to add more use cases with some working samples.  And finally, similar to @tsimbalar and his awesome [notes](https://github.com/tsimbalar/serilog-settings-comparison/tree/master/docs) I have been trying to write up some examples on my [blog](https://merbla.com/categories/exploring-serilog-v2/
).

I understand this does not answer the question, rather I hope it gives some insight and information to drive the conversation forward to help on boarding new users more seamlessly.

**Comment by tsimbalar** [comment]
Thanks @merbla for the blog posts, I hadn't seen your latest articles about Serilog. Really cool ! 

The Serilog ecosystem has grown so much that maintaining all its documentation in a centralized location and keeping it up-to-date would be a huge endeavor. 

It is also true that the Wiki features of GitHub have some limitations (for instance, one cannot issue a PR with changes to apply to the wiki) that make it harder to accept contributions.

I kind of wish we had a more "unified"/discoverable documentation entry point where documentation from all the repos would be browsable "in-place" (without navigating through repos and more repos), and where maintainers of each repo can update and add content.

For specific use-cases like "how do I do this ...", I still believe the community-provided content is the best approach (blogs, gists, stackoverflow) and having a page with links to those could be useful.

**Comment by MV10** [comment]
Weird, I've never noticed you can't PR a wiki. That's too bad.

I started using Serilog just three months ago, so I have fresh memories of the amount of time and research it required just figuring out what all the new terminology implied and how all the pieces fit together. The samples with each repo are generally interesting but they're also rather random. I ended up doing a lot of the "repos and more repos" thing @tsimbalar just described, as well as the dreaded go-read-the-code (my big pet peeve with the current state of Microsoft's docs...).

I'm the oddball sort of developer who actually likes documenting things. I realize it's an uphill battle, but I'd contribute to the documentation repo I mentioned earlier if enough folks felt like getting some kind of plan together to tackle the effort. It's certainly a big job, more than any one person could ever handle, but it strikes me as worthwhile.

**Comment by tsimbalar** [comment]
I have created a _discussion_ issue to the core Serilog repo : serilog/serilog#1164 

This would allow to keep the discussion going in a more central place ;)

**Comment by tsimbalar** [comment]
Closing this issue as the discussion is now moved to serilog/serilog#1164 .

Cheers !
