### ISSUE TITLE
Ignore MinimumLevel:Default from appsettings.json

### ISSUE THREAD

**Issue by TerraVenil** [serilog/serilog-settings-configuration#116]
I have basic following configuration:
https://github.com/TerraVenil/serilog-settings-configuration/tree/I/SS-1

I would expect if I downgrade log level from Error to Information I would see in console both Hello, world! messages insted I see only one. As I understand when you call throught reflection Console.WriteTo you pass alway log level Verbose.
So is it expected behaviour that I can't downgrade from Error to Information if I manually configure logger?

**Comment by tsimbalar** [comment]
Hi Alexey,

I could not reproduce the issue you mentioned.

If I take the Sample app from serilog-settings-comparison and run it, I see the expected behavior : 

with 
```json
    "MinimumLevel": {
      "Default": "Error",
      "Override": {
        "Microsoft": "Warning",
        "MyApp.Something.Tricky": "Verbose"
      }
    },
```

![image](https://user-images.githubusercontent.com/160544/42243767-b72e3a32-7f12-11e8-9b80-5d97e7d229bb.png)


and with

```json
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "MyApp.Something.Tricky": "Verbose"
      }
    },
```

![image](https://user-images.githubusercontent.com/160544/42243829-e3a80084-7f12-11e8-969c-cacfc2016d03.png)

Is there something special that you are doing that I could be missing ?

**Comment by TerraVenil** [comment]
It works as expected ONLY when `WriteTo.Console` initialized with Verbose level and then you can elevetate level to Warning, Error but if you initialized `WriteTo.Console` for example with Error level you can't downgrade level of logging. Just to clarify, is it expected behaviour?.

**Comment by tsimbalar** [comment]
Ah ok.

Yest this is the intended behavior. 
`.MinimumLevel`applies to the whole logging pipeline, and any event written with a level lower than that level will basically be discarded and will not reach any of the sinks, no matter the value of the `restrictedToMinimumLevel` value of the sink configuration.

You can read a bit more about it in the *Serilog* wiki : https://github.com/serilog/serilog/wiki/Configuration-Basics#minimum-level
