### ISSUE TITLE
Question: what changes are honored with reloadOnChange?

### ISSUE THREAD

**Issue by mdebeus** [serilog/serilog-settings-configuration#154]
I've basically copied your sample, so I am using almost the exact same configuration you have specified in your appsettings.json (except I put the log files somewhere else). I tried changing the path to my log file - the one in Async-File from .\\Logs\serilog-configuration-sample.txt to .\\Logs\MyLogs\\serilog-configuration-sample.txt but that change was not picked up, and I only have the one log file in .\\Logs.

I also tried changing the outputTemplate, but that change was not picked up either.

I am using this in asp.net core.

**Comment by tsimbalar** [comment]
Hi ,

If I remember properly, the only changes that can be honored are the ones related to `MinimumLevel`. 

https://github.com/serilog/serilog-settings-configuration/blob/71ee59dad1739f38a4910d1e84404d97e2e1b90c/src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs#L126-L143

A logging pipeline is "immutable by design" once it has been created, so it can no longer be altered. The only parts of the logging pipeline that support some sort of *dynamic* updates are the level, the same way you would work with a `LoggingLevelSwitch` in your code.

I thinks we were mentioning some doubts about that part here as well : https://github.com/serilog/serilog-settings-configuration/issues/99

**Comment by skomis-mm** [comment]
Tracked until we have updated documentation.

**Comment by andyvig** [comment]
Is there an example of how to make config reloading work?  I downloaded the sample and changes to the minimumLevel in the config file don't seem to take effect without restarting the app.

**Comment by skomis-mm** [comment]
Hi, @andyvig , make sure you pass `reloadOnChange: true` to the config file you change at runtime (AddJsonFile(..)). 

Changes to top-level `MinimumLevel` section `LevelSwitches` are respected for dynamic update

**Comment by skomis-mm** [comment]
Documentation was updated
