### ISSUE TITLE
Override fails if no dot after override prefix. Document this behaviour? Or fix?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [serilog/serilog-settings-configuration#177]
When `System.Threading<5>` - fails. 

```
        [Fact]
        public void TestMinimumLevelOverridesForChildContext()
        {
            var json = @"{
                ""Serilog"": {
                    ""MinimumLevel"" : {
                        ""Default"" : ""Warning"",
                        ""Override"" : {
                            ""System"" : ""Warning"",
                            ""System.Threading"": ""Debug""
                        }
                    }
                }
            }";

            LogEvent evt = null;

            var log = ConfigFromJson(json)
                .WriteTo.Sink(new DelegatingSink(e => evt = e))
                .CreateLogger();

            log.Write(Some.DebugEvent());
            Assert.Null(evt);

            var custom = log.ForContext(Constants.SourceContextPropertyName, typeof(System.Threading.Tasks.Task).FullName + "<42>");
            custom.Write(Some.DebugEvent());
            Assert.NotNull(evt);


            evt = null;
            var systemThreadingLogger = log.ForContext<System.Threading.Tasks.Task>();
            systemThreadingLogger.Write(Some.DebugEvent());
            Assert.NotNull(evt);

            evt = null;
            var custom2 = log.ForContext(Constants.SourceContextPropertyName,"System.Threading.Tasks.Task<5>");
            custom2.Write(Some.DebugEvent());
            Assert.NotNull(evt);

            evt = null;
            var custom3 = log.ForContext(Constants.SourceContextPropertyName,"System.Threading<5>");
            custom3.Write(Some.DebugEvent());
            Assert.NotNull(evt);
        }
```

**Comment by tsimbalar** [comment]
Hi Dzmitry,

I think this issue should be in the core https://github.com/serilog/serilog repo, as it has to do with the core implementation of `Minimum Level overrides`. 

I think it is by design. 

Minimum level overrides work by namespace, which are `dot`-separated. This is to ensure that `SourceContext` with value `"System.Foo.Bar"` and `"System.Foo.Barcelona"` are considered different, even though they both start with `System.Foo.Bar`. 

FYI this is implemented here : https://github.com/serilog/serilog/blob/dev/src/Serilog/Core/LevelOverrideMap.cs 

It could probably be extended to also work with other *non alpha-numerical* characters, but it might introduce some performance impact or some subtle behavior change, for instance for people who have generics as `SourceContext` ... 

To be checked with @nblumhardt  and @serilog/reviewers-core ;)

**Comment by dzmitry-lahoda** [comment]
In terms of behaviour I have eventually thought of exactly that. Thanks for pointing into serilog core code.

So issue may be closed. Could be found via search. 

Other solution could be add documentation about that somewhere. Log warning?
