### ISSUE TITLE
Is it possible to decrypt the connection string while doing MSSQLServer Sink

### ISSUE THREAD

**Issue by manjunathdl66** [serilog/serilog-settings-configuration#182]

**Comment by manjunathdl66** [comment]
In My situation i will store the connection string with Username and Password encrypted. So while sinking i want to decrypt and pass to Serilog Sink i should use ReadFrom.Config()

Can some one help me with example.

**Comment by skomis-mm** [comment]
Sorry for a late response, @manjunathdl66 . 
The issue is not related to this project, but to `Microsoft.Extensions.Configuration` in general. I believe it can be accomplished. 

Some links to help: [encrypted-configuration-aspnet-core](https://stackoverflow.com/questions/36062670/encrypted-configuration-in-asp-net-core), [decrypt-config-settings-aspnet-core](https://visualstudiomagazine.com/articles/2019/09/26/decrypting-config-settings.aspx).
