### ISSUE TITLE
Azure Functions - Enrich Properties Unable to be Resolved

### ISSUE THREAD

**Issue by anAgent** [serilog/serilog-settings-configuration#190]
Hello, 

I've been trying to get the resolution of the "Enrich" properties to be found working with an Azure Function 2.1. What I've noticed is that since the loaded Assembly is not the actual function itself, the package is unable to resolve the assemblies.  I've created a repository with a coded solution where you can witness this happening. You can find it here: [anAgent/AzFunctionSerilog](https://github.com/anAgent/AzFunctionSerilog)

Using the following code, you can basically see what the underling AssemblyFinder seems to be doing. Of course, this is not it's exact code, but inspecting the **context** displays the same information that is being constructed within the code.

```csharp
            var assembly = Assembly.GetEntryAssembly();
            var context =   DependencyContext.Load(assembly);

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(ConfigurationHelper.ConfigurationRoot, context)
                .CreateLogger();
```
The actual loaded Assembly is not a compiled dll of the function. Is there a way to point the DependencyContext to a different location for it to find the serilog dll's? I.e. `.\netcoreapp2.2\bin`

And finally, thank you for this package! I'll continue to look at the code to see if I can figure something out as well.

**Comment by anAgent** [comment]
We were able to figure out a solution to resolve the dependencies. I've created a PR that I hope either works as you would like or a good start to a solution: 
https://github.com/serilog/serilog-settings-configuration/pull/191

**Comment by anAgent** [comment]
Just an update that I updated PR #191 with some comments on this topic.

**Comment by skomis-mm** [comment]
Hi @anAgent ,

Sorry for a long delay. Just have now a bit time to sorts things..
```csharp
var context =   DependencyContext.Load(assembly);
```
This is the right way. But you need to pass assembly from the function itself, not the host assembly. But as you pointed in PR `.deps.json` file sits in azure function specific folder, not with other dll's like for other .net core projects. So you basically need to add msbuild tasks in function csproj to align with other .net core projects:

```xml
<Target Name="FunctionsPostBuildDepsCopy" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(OutDir)$(AssemblyName).deps.json" DestinationFiles="$(OutDir)bin\$(AssemblyName).deps.json" />
</Target>

<Target Name="FunctionsPublishDepsCopy" AfterTargets="Publish">
    <Move SourceFiles="$(PublishDir)$(AssemblyName).deps.json" DestinationFiles="$(PublishDir)bin\$(AssemblyName).deps.json" />
</Target>
```
(I just copy/pasted modified version from `Microsoft.NET.Sdk.Functions` msbuild tasks)

and then initialize dependency context like:
```csharp
var functionDependencyContext = DependencyContext.Load(typeof(Startup).Assembly);
...
var logger = new LoggerConfiguration()
       .ReadFrom.Configuration(config, dependencyContext: functionDependencyContext)
       .CreateLogger();
```

The second and oldest way without do anything specific to Azure Functions is to use `Using` section to specify assemblies that needs to be loaded prior configuration. Taking your sample from `AzFunctionSerilog` it will look like this:
```json
 "Serilog": {
    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.ApplicationInsights", "Serilog.Enrichers.Thread", "Serilog.Enrichers.Environment" ],
    "MinimumLevel": {
      "Default": "Verbose"
    },   
```
I just discovered, that currently `Serilog` also should be added to `Using` list, otherwise `Serilog`'s configurations like `FromLogContext(..)` won't work. Looks like a bug that should be fixed!
