### ISSUE TITLE
Disable programmatic configuration via JSON configuration

### ISSUE THREAD

**Issue by alexdresko** [serilog/serilog-settings-configuration#204]
If I've programmatically configured a sink or enricher, is it possible to disable that sink or enricher via the JSON file? 

Related question: Does the JSON configuration override the programmatic configuration?

**Comment by nblumhardt** [comment]
Hi @alexdresko - no, to both questions - programmatic and JSON configuration are completely separate.

If it's a normal part of your app configuration (rather than just something opportunistic), using regular key-value settings from the JSON file to configure the logger can work well. Let me know if you need a hand exploring this option.

Best regards,
Nick
