### ISSUE TITLE
Impossible to use with WPF application?

### ISSUE THREAD

**Issue by rrosic** [serilog/serilog-settings-configuration#21]
Am I missing something or this is impossible to use in plain WPF application?
There is no project.json file and default DependencyContext for WPF is null.

**Comment by rrosic** [comment]
I managed to create project.json file and get it to update after package install but DependencyContext is still null.

**Comment by nblumhardt** [comment]
Hi Robert - I would guess that there's some way to create a `new DependencyContext()` and pass it into the `ReadFrom.Configuration()` method, but I haven't investigated what's required.

Looking at how we use it in this library, I think a good improvement would be for us to break the explicit dependency on this type so that we can use the full framework's reflection capabilities when they're available.

**Comment by nblumhardt** [comment]
Rolling this into #20. Any help appreciated. Thanks for the report!
