### ISSUE TITLE
Logging configuration with EF core throws error

### ISSUE THREAD

**Issue by Thaoden** [serilog/serilog-settings-configuration#25]
When I specify a logging configuration to be read from the configuration file by

    Log.Logger = new LoggerConfiguration().ReadFrom.Configuration(Configuration).CreateLogger();

and then try to create a migration, EF Core complains that there is no default public constructor on my Context class. When I remove the `ReadFrom.Configuration(Configuration)` part and instead define my logging config using the fluent API, EF Core doesn't throw anything.

Any hints where this behaviour might come from?

**Comment by skomis-mm** [comment]
@Thaoden , where do you initialize logging?
Ef commands indeed will not work on full .net and if you initializing logging inside Context type of in the factory because they don't contain compilation context. If my guess  is correct. try to update the package to the latest dev `2.2.0-*`

**Comment by Thaoden** [comment]
@skomis-mm The logging is initialized in the `Startup.cs` constructor.
Updating to version `2.2.0-dev-00035` indeed did the trick.

**Comment by skomis-mm** [comment]
@Thaoden , still not sure how did you get there. Did you have exception at runtime or at design time while applying ef command like `dotnet ef migrations add <Migration> -c <ContexT>`?

**Comment by Thaoden** [comment]
@skomis-mm The error occurs while applying the `dotnet ef migrations add <Migration>` command.

**Comment by skomis-mm** [comment]
@Thaoden , I see, interesting.

Seems like in a web type projects when there is no default ctor on `Context`  ef command first tries to create it via DI and `Startup` class, but it fails because compilation context is null. In the error message they also recommend create design time [context factory](https://docs.efproject.net/en/latest/miscellaneous/configuring-dbcontext.html#using-idbcontextfactory-tcontext). If Startup fails it calls `Create` on this factory. Anyway, the source issue the same.

**Comment by Thaoden** [comment]
@skomis-mm So what has changed between `2.1.0` and `2.2.0-dev-00035` that enables the use of the configuration-file based logger?

**Comment by skomis-mm** [comment]
@Thaoden , [removed](https://github.com/serilog/serilog-settings-configuration/issues/20) requirement on `preserveCompilationContext=true` for the full .NET. It is now optional.

**Comment by Thaoden** [comment]
@skomis-mm I see. Thanks!
