### ISSUE TITLE
The purpose of the "using" subsection?

### ISSUE THREAD

**Issue by aggieben** [serilog/serilog-settings-configuration#34]
In the examples, there is often a `Using` property as well as a `WriteTo`, like the one at the top of the README.md:

```json
{
  "Serilog": {
    "Using":  ["Serilog.Sinks.Literate"],
    "MinimumLevel": "Debug",
    "WriteTo": [
      { "Name": "LiterateConsole" },
      { "Name": "File", "Args": { "path": "%TEMP%\\Logs\\serilog-configuration-sample.txt" } }
    ],
    "Enrich": ["FromLogContext", "WithMachineName", "WithThreadId"],
    "Properties": {
        "Application": "Sample"
    }
  }
}
```

What is the purpose of the `Using` property, and why would you want both?  Why wouldn't the above be this instead?

```json
{
  "Serilog": {
    "MinimumLevel": "Debug",
    "WriteTo": [
      { "Name": "LiterateConsole" },
      { "Name": "File", "Args": { "path": "%TEMP%\\Logs\\serilog-configuration-sample.txt" } }
    ],
    "Enrich": ["FromLogContext", "WithMachineName", "WithThreadId"],
    "Properties": {
        "Application": "Sample"
    }
  }
}
```

**Comment by nblumhardt** [comment]
Hi Ben, thanks for the note. It's sometimes necessary to list assemblies so that they can be loaded and searched for sink/enricher configuration methods. Serilog does its best to find them, so it's not always required, but in some cases (full .NET Framework especially) a `Using` block might still be needed.

Does this help?

Cheers,
Nick

**Comment by aggieben** [comment]
Yes, that makes sense, thank you.
