### ISSUE TITLE
Configure sub-loggers through JSON appsettings

### ISSUE THREAD

**Issue by arielcloud** [serilog/serilog-settings-configuration#37]
something like:
```
"WriteTo": [
      {
        "Name": "Email",
        "Args": {
          ...
        },
        ***"Filter"***:  #....
      },
]
```
10x!

**Comment by nblumhardt** [comment]
Regular Serilog configurations use `WriteTo.Logger()` for this:

```csharp
    .WriteTo.Logger(lc =>
        .Filter.ByIncludingOnly(...)
        .WriteTo.Email(...))
```

There's no equivalent syntax yet for configuration, mostly because we only just got a [configuration-compatible filtering provider](https://nblumhardt.com/2017/01/serilog-filtering-dsl/).

An extension to the JSON configuration syntax to do this would be great.
