### ISSUE TITLE
Misconfigured sinks fail silently

### ISSUE THREAD

**Issue by FantasticFiasco** [serilog/serilog-settings-configuration#52]
I would like to inquire the behavior where a misconfigured sink silently fails, in the aspect of not being created and configured in Serilog.

I'm on the verge of doing some work on two Serilog sink, work that would involve renaming arguments in the extension methods creating the sink. However I am afraid to do so because from the perspective of the consumers, even though I indicate my changes as breaking, they wouldn't notice at build, the application wouldn't throw an exception at runtime, the only behavioral change they would be able to notice would be the absence of log event from this particular sink.

What is the reasoning behind not throwing an exception when the JSON is misconfigured?

**Comment by nblumhardt** [comment]
Hi @FantasticFiasco - the current thinking is that JSON configuration issues are in the "runtime" category - https://github.com/serilog/serilog/wiki/Reliability#configuration - not sure whether this is optimal, but had to pick one.

Would improving the `SelfLog` output generated from misconfigured sinks help here?

**Comment by FantasticFiasco** [comment]
Would all JSON configuration errors have to fall into the same category? Wouldn't the full range of configuration errors in C# also be applicable to JSON?

From my perspective, JSON and C# configuration are just two sides of the same coin, and whether or not something is a _runtime configuration error_ or a _development-time invariant violation_ would be for the sink to decide.

Let me try to explain using the code example for the development-time invariant violation.

```
// Null is never acceptable as a filename, so
// Seriog will throw ArgumentNullException here.
Log.Logger = new LoggerConfiguration()
    .WriteTo.File(null)
    .CreateLogger();
```

Converting this to JSON and we would end up with something like this:

```
{
  "Serilog": {
    "WriteTo": [
      {
        "Name": "File",
        "Args": { }
      }
    ]
  }
}
```

Running these two configurations produce different behavior. The first will throw an exception, but the second won't, it will silently fail. I am guessing that the reason for this is that `Serilog.Settings.Configuration` can't find a suitable extension method since `path` is required, would that be a valid guess?

I think the point I am trying to make is that if `Serilog.Settings.Configuration` cannot delegate the responsibility to the sink, letting it determine whether the error is a runtime configuration error or a development-time invariant violation, then it should fall back to assume it to be a development-time invariant violation.

**Comment by nblumhardt** [comment]
Thanks for the follow-up!

Your reasoning is fair; the other consideration is that JSON configuration is sometimes modified at deployment time, unlike the code-based configuration which is generally static. When this behaviour was inherited from the `<appSettings>` provider, the thinking was that a misconfigured `appsettings.Environment.json` shouldn't bring down a production deployment (since it's very unlikely this file could be loaded and tested at development-time).

Serilog does already take a much more aggressive approach to surfacing configuration errors than most of its predecessors. I am hesitant to tighten this up further, but perhaps passing something like `strictValidation: true` could opt into this? To provide it consistently across key-value pair, XML and JSON settings providers might take quite a bit of work, but it seems viable. Thoughts?

**Comment by FantasticFiasco** [comment]
> I am hesitant to tighten this up further

I understand this, its hard to get a ratio of the developers happy with this change and the once in the other camp

> Thoughts?

The idea of opting in to validate the JSON is also something I've thought about, but I didn't wan't to start this issue with a compromise :-) i think it is a good idea!

**Comment by nblumhardt** [comment]
If anyone's keen to tackle this, please chime in - closing for now as i don't think we'll make progress on it in the near future.
