### ISSUE TITLE
Target netstandard1.3 instead of netstandard1.6

### ISSUE THREAD

**Issue by maximpashuk** [serilog/serilog-settings-configuration#60]
I just analyzed your library dependencies.

Serilog
- version 2.0.0 (current ref) requirement is netstandard1.0

Microsoft.Extensions.Configuration.Abstractions
- version 1.0.0 (current ref) requirement is netstandard1.0

Microsoft.Extensions.DependencyModel
- version 1.0.0 (current ref) requirement is netstandard1.6
- version 1.1.2 (leatest at this time) requirement is netstandard1.3

So, if you update your packages dependencies to latest versions you can target your lib to netstandard1.3 instead of netstandard1.6.

This adds more compatibility to your lib.
Please do this.

**Comment by nblumhardt** [comment]
Thanks for checking this out, @maximpashuk!

Definitely open to a PR for this, if anyone's interested in taking a shot 👍

**Comment by peitschie** [comment]
I had a quick crack at this (there are bugs related to ValueType in .NET framework 4.7, which are a total pain....). It seems that Microsoft.Extensions.DependencyModel was only able toa chieve this reduction in requirements by omitting the paths that required Assembly.GetEntryAssembly:

https://github.com/dotnet/core-setup/blob/2f5cf7e8a8d15e79e928455da89d61a738f926df/src/managed/Microsoft.Extensions.DependencyModel/DependencyContext.cs#L51-L53

The change to `ConfigurationLoggerConfigurationExtensions` is trivial to make, but I am concerned that causing the `dependencyContext` to be `null` by default makes it practically useless, as this means `ConfigurationReader.GetSerilogConfigurationAssemblies` is always an empty collection when used via .NET standard.

**Comment by peitschie** [comment]
Here's an example of how the patch might be: https://github.com/serilog/serilog-settings-configuration/compare/dev...peitschie:dev

I'm not a real big fan of it to be honest...

**Comment by nblumhardt** [comment]
Thanks for the follow-up @peitschie. Instead of creating the `DefaultDependencyContext` property, why not just pass an instance of the context through to the configuration method directly? Cheers!

**Comment by peitschie** [comment]
@nblumhardt I was attempting to reduce the impact to my own usage of serilog 😄 . I have 2-3 independent loggers that are configured separately in my system and wanted a way to set the dependency context across all consumers of the log configuration, without needing to pass it in to each configure call. If I went the injection approach (which the api already supports) I'd need to pass the dependency context in a few places, or share it statically.

What would you think of the following tweaks:
1. Drop the `DefaultDependencyContext` (it's hard to discover, and I don't like it as an approach)
2. Drop the null default value for .NET standard, so a consumer via that interface is forced to supply a dependency context. This helps avoid undesirable behaviour, as having this value as implicitly null for the .NET standard looks like it effectively disables the configuration (`GetSerilogConfigurationAssemblies` will always be empty).

The new configuration extensions would be something like:
```
public static class ConfigurationLoggerConfigurationExtensions
{
    ...

#if !NETSTANDARD1_3
    public static LoggerConfiguration ConfigurationSection(
        this LoggerSettingsConfiguration settingConfiguration,
        IConfigurationSection configuration)
    {
        ...
    }
#endif

    public static LoggerConfiguration ConfigurationSection(
        this LoggerSettingsConfiguration settingConfiguration,
        IConfigurationSection configuration,
        DependencyContext dependencyContext)
    {
        ...
    }
}
```

An alternative approach is exploit the fact that though `DependencyContext.Default` is not included in the standard, it *is* almost guaranteed available at runtime on the concrete type the standard has redirected to. This means that I can use reflection to look this up at runtime for the .NET standard version. E.g.,:
```
        /// <summary>
        /// Get the default DependencyContext for the platform
        /// </summary>
        /// <returns>The default dependency context used for assembly resolution.</returns>
        public static DependencyContext GetDefaultDependencyContext()
        {
#if !NETSTANDARD1_3
            return Assembly.GetEntryAssembly() != null ? DependencyContext.Default : null;
#else
            // This check is required due to https://github.com/Microsoft/vstest/issues/649
            var getEntryAssemblyMethod = typeof(Assembly).GetTypeInfo().GetDeclaredMethod("GetEntryAssembly");
            if (getEntryAssemblyMethod != null && getEntryAssemblyMethod.Invoke(null, new object[0]) != null)
            {
                var defaultProperty = typeof(DependencyContext).GetTypeInfo().GetDeclaredProperty("Default");
                if (defaultProperty != null)
                {
                    return (DependencyContext)defaultProperty.GetValue(null);
                }
            }
            return null;
#endif
        }
```

This has advantage of preserving the current behaviour almost fully... though it is admittedly a hack to allow the .NET standard level to be lowered. I've included a test showing this behaviour works properly... except it doesn't work properly in .NET Framework due to https://github.com/Microsoft/vstest/issues/649. Hah... sometimes I love this new .NET thing!

I've updated my branch, replacing the first commit with option 1, and adding a commit that changes it to option 2 (just to prove that it is viable).

Happy for more thoughts!

**Comment by peitschie** [comment]
@nblumhardt just checking in to see if you have any preference on patch 1 or patch 2? I will raise it in a PR once the direction is set 😄

**Comment by nblumhardt** [comment]
Hi Philip, thanks for the nudge :-)

This all looks like a bit of hassle just to extend support from .NET 4.6.1 back to 4.6 - especially if we're stuck with subtle behavior differences, and the opportunity for people to hit `MissingMethodException` (always sure to generate a few issue reports).

Is the additional platform support a blocker for many people, given it all relies on brand new libraries such as _Microsoft.Settings.Configuration_ anyway? (Just sanity checking :-))

Thoughts?

**Comment by peitschie** [comment]
> This all looks like a bit of hassle just to extend support from .NET 4.6.1 back to 4.6

Are you able to double-check that? Playing locally, .NET standard 1.6 seems to require .NET Framework 4.7 for me (unless I'm doing something wrong)?

**Comment by nblumhardt** [comment]
Sorry about the imprecision. The 2.0 build tooling is needed for this targeting combination to work:

https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by peitschie** [comment]
Ah! That makes perfect sense. Yes, in this case, I agree it's not worth changing 😄 

The best type of issue closure is one that requires no code changes, right? 😁

**Comment by nblumhardt** [comment]
+1 to that! :-)

Thanks for all the input :+1:
